Kotlin 2.4.0, Gradle

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,25 +21,35 @@ jobs:
           distribution: 'liberica'
           architecture: x64
           check-latest: true
-          cache: maven
+          cache: gradle
+          # cache: maven
 
-      - name: Build by maven wrapper
+      # - name: Build by maven wrapper
+      #   env:
+      #     MAVEN_OPTS: >-
+      #       -Dmaven.wagon.http.timeout=120000
+      #       -Dmaven.wagon.rto=120000
+      #       -Dmaven.wagon.http.retryHandler.count=5
+      #       -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
+      #   run: chmod +x ./mvnw; ./mvnw -B -U package
+      # #          for i in 1 2 3; do
+      # #            ./mvnw -B -U -ntp package && break
+      # #            if [ "$i" -eq 3 ]; then
+      # #              echo "Maven build failed after 3 attempts"
+      # #              exit 1
+      # #            fi
+      # #            echo "Retrying Maven build ($i/3 failed)..."
+      # #            sleep 10
+      # #          done
+
+      - name: Build by gradle wrapper (assemble)
         env:
-          MAVEN_OPTS: >-
-            -Dmaven.wagon.http.timeout=120000
-            -Dmaven.wagon.rto=120000
-            -Dmaven.wagon.http.retryHandler.count=5
-            -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
-        run: chmod +x ./mvnw; ./mvnw -B -U package
-#          for i in 1 2 3; do
-#            ./mvnw -B -U -ntp package && break
-#            if [ "$i" -eq 3 ]; then
-#              echo "Maven build failed after 3 attempts"
-#              exit 1
-#            fi
-#            echo "Retrying Maven build ($i/3 failed)..."
-#            sleep 10
-#          done
+          GRADLE_OPTS: >-
+            -Dorg.gradle.internal.http.connectionTimeout=120000
+            -Dorg.gradle.internal.http.socketTimeout=120000
+        run: |
+          chmod +x ./gradlew
+          ./gradlew --no-daemon --refresh-dependencies assemble
 
       - name: Upload a Build Artifact
         uses: actions/upload-artifact@v6
